var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/submit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ni.xh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0n6_f5s.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~0x98s._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tyfoz0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_submit_page_actions_0pqd_gn.js")
R.m(91885)
module.exports=R.m(91885).exports
