var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/scrapers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__07ia4o0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0i6i-61.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~0x98s._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tyfoz0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_admin_layout_tsx_12a.fw9._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_scrapers_page_actions_13mzw2j.js")
R.m(85815)
module.exports=R.m(85815).exports
