var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/update-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e.iixx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0athb_m.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~0x98s._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tyfoz0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_update-password_page_actions_0kzn4im.js")
R.m(77260)
module.exports=R.m(77260).exports
